#!/bin/zsh
# This is a real basic deployment script
autoload -U colors && colors
#
### Set these variables
dockerHost=$DOCKERPROD
hipchat_token=$HIPCHAT_API_TOKEN
meetspace_token=$MEETSPACE_API_TOKEN
ms_teamname=$MEETSPACEBOT_TEAM
###

echo "$fg[blue]"

case "$1" in
  status)
    ssh $dockerHost "sudo docker ps -a"
    echo "$fg[none]"
    exit 0
    ;;
  log|logs)
    ssh $dockerHost "sudo docker logs -f msb-1"
    echo "$fg[none]"
    exit 0
    ;;
  start)
    ssh $dockerHost "sudo docker start msb-1"
    ssh $dockerHost "sudo docker ps -a"
    echo "$fg[none]"
    exit 0
    ;;
  clean)
    d_list=$(ssh $dockerHost "sudo docker ps -aq")
    i_list=$(ssh $dockerHost "sudo docker images -aq")
    ssh $dockerHost "sudo docker kill $d_list"
    ssh $dockerHost "sudo docker rm $d_list"
    ssh $dockerHost " sudo docker rmi $i_list"
    ;;
  deploy)
    echo "$fg[yellow] # Starting Compile #"
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o releases/meetspaceBot .
    if [ $? != 0 ]; then
      echo "$fg[red] !! Failed to build"
      echo "$fg[none]"
      exit 1
    fi
    echo "$fg[yellow] # Compile Finished #"
    echo "$fg[yellow] ##  Starting Container Build ##"
    echo "$fg[blue]"
    docker build -q --no-cache -t meetspacebot .
    imageID=$(docker images -q meetspacebot:latest)
    docker tag $imageID davyj0nes/meetspacebot:latest
    echo "$fg[yellow] ###  Pushing Container to Registry ###"
    echo "$fg[blue]"
    docker push davyj0nes/meetspacebot

    running=$(ssh $dockerHost "sudo docker ps -q -f name=msb-1")
    if [ "$running" != "" ]; then
      echo "$fg[red]## Container Running ##"
      echo "$fg[red]...Removing..."
      ssh $dockerHost "sudo docker kill msb-1 && sudo docker rm msb-1"
      echo "$fg[green]Container Removed"
      ssh $dockerHost "sudo docker ps"
    fi
  
    echo "$fg[yellow]### Starting Container ####" 
    echo "$fg[blue]"
    ssh $dockerHost "sudo docker pull davyj0nes/meetspacebot && \
      sudo docker run --restart=unless-stopped -p 80:8081 -d --name msb-1 -e HIPCHAT_API_TOKEN="$hipchat_token" -e MEETSPACE_API_TOKEN="$meetspace_token" -e MEETSPACEBOT_TEAM="$ms_teamname" davyj0nes/meetspacebot"
    echo "## Container Running"
    ssh $dockerHost "sudo docker ps -a"
    echo "$fg[none]"
    exit 0
    ;;
  *)
    echo "$fg[red] Unknown Command"
    echo "$fg[yellow] Usage:"
    echo "$fg[yellow]   deploy <command>"
    echo "$fg[yellow]   - status [Show docker ps]"
    echo "$fg[yellow]   - log    [Follow logs of container]"
    echo "$fg[yellow]   - deploy [Deploy new version to prod]"
    echo "$fg[yellow]   - clean  [Tidy up containers]"
    echo "$fg[none]"
    exit 1
    ;;
esac
